print("Program starting.")
print("Estimate how many minutes you spent on programming...")
t1 = float(input("\nA1_T1:"))
t2 = float(input(" A1_T2:"))
t3 = float(input(" A1_T3:"))
t4 = float(input(" A1_T4:"))
t5 = float(input(" A1_T5:"))
t6 = float(input(" A1_T6:"))
t7 = float(input(" A1_T7:"))
sumt =round(t1+t2+t3+t4+t5+t6+t7)
avg = round(sumt/7, 2)
r = round(avg)
print(" \nIn total you spent", sumt, "minutes on programming.")
print("Average per task was", avg, "min and same rounded to the nearest integer", r, "min.")
print("\nProgram ending.")
